from src.exception import CustomException
from src.logger import logging
import pandas as pd
import os
import numpy as np
import sys
from datetime import datetime

def read_from_csv_file(file_path: str) -> pd.DataFrame:
    try:
        logging.info(f"reading csv file at: {file_path}")
        df = pd.read_csv(file_path)
        logging.info(f"Finished reading csv file at: {file_path}")
        return df
    except Exception as e:
        raise CustomException(e)
